name: Daily arXiv Scraper

on:
  schedule:
    # Run daily at 00:00 UTC and 12:00 UTC
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Add write permissions for GITHUB_TOKEN
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Use the automatic token
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install arxiv
        
    - name: Run daily arXiv scraper
      run: |
        ls
        cd scraping
        ls
        python scraper.py --daily
        
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add scraping/daily/
        git commit -m "Add daily arXiv data for $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push
